Create corrected_wrong
This is the exact error message I am receiving in my terminal when running the code "/home/project/banks_project.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd
Traceback (most recent call last):
  File "/home/project/banks_project.py", line 55, in <module>
    df = extract(url, table_attribs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/project/banks_project.py", line 30, in extract
    bank_name = col[1].find_all('a')[1]['title']
                ~~~^^^
IndexError: list index out of range"